#!/bin/sh

. /apl/soft/lsf/conf/profile.lsf

LSF_INCDIR=/apl/soft/lsf/7.0/include

set -x
g++ \
  -Isrc \
  src/lsfutils.cxx \
  src/JobList.cxx \
  src/JobInfoEntry.cxx \
  src/JobSubmitEntry.cxx \
  src/OutputGE_02.cxx \
  -o lsfutils -Wall \
  -I$LSF_INCDIR \
  $LSF_LIBDIR/libbat.a \
  $LSF_LIBDIR/liblsf.a \
  -g -lm -lnsl -ldl

g++ \
  -Isrc \
  src/blsof.cxx \
  src/JobList.cxx \
  src/JobInfoEntry.cxx \
  src/JobSubmitEntry.cxx \
  src/OutputGE_02.cxx \
  -o blsof -Wall \
  -I$LSF_INCDIR \
  $LSF_LIBDIR/libbat.a \
  $LSF_LIBDIR/liblsf.a \
  -g -lm -lnsl -ldl

